import type { MenuItem, MenuCategory, CategoryGroup } from "./types";

// ─── CATEGORY METADATA ────────────────────────────────────────────────────────

export const categoryLabels: Record<MenuCategory, string> = {
  beverages: "Beverages",
  refreshments: "Refreshments",
  sandwiches: "Sandwiches",
  snacks: "All Day Snacks",
  "south-india": "Taste of South India",
  soups: "Soups",
  pizzas: "Pizzas",
  "pav-bhaji": "Pav Bhaji",
  tandoori: "Tandoori Snacks",
  hindustani: "Hindustani Khasiyat",
  breads: "Mehek Tandoor ki",
  rice: "Basmati Khazana",
  "chinese-starters": "Chinese Starters",
  "chinese-mains": "Chinese Main Course",
  sizzlers: "Continental & Sizzlers",
  salads: "Salads, Raitas & Papads",
  desserts: "Desserts",
  milkshakes: "Milk Shakes",
  mastanis: "Mastanis & Faloodas",
  juices: "Fresh Fruit Juices",
  "ice-cream": "Natural Ice Cream",
};

export const categoryEmojis: Record<MenuCategory, string> = {
  beverages: "☕",
  refreshments: "🥤",
  sandwiches: "🥪",
  snacks: "🍟",
  "south-india": "🫓",
  soups: "🍲",
  pizzas: "🍕",
  "pav-bhaji": "🍞",
  tandoori: "🔥",
  hindustani: "🍛",
  breads: "🫓",
  rice: "🍚",
  "chinese-starters": "🥢",
  "chinese-mains": "🍜",
  sizzlers: "♨️",
  salads: "🥗",
  desserts: "🍨",
  milkshakes: "🥛",
  mastanis: "🍦",
  juices: "🍊",
  "ice-cream": "🍦",
};

// Navigation groups for the menu page
export const categoryGroups: CategoryGroup[] = [
  { label: "Drinks", categories: ["beverages", "refreshments", "juices"], emoji: "☕" },
  { label: "Snacks", categories: ["sandwiches", "snacks", "south-india", "soups", "pizzas", "pav-bhaji", "tandoori"], emoji: "🍟" },
  { label: "Main Course", categories: ["hindustani", "breads", "rice"], emoji: "🍛" },
  { label: "Chinese", categories: ["chinese-starters", "chinese-mains"], emoji: "🥢" },
  { label: "Continental", categories: ["sizzlers", "salads"], emoji: "♨️" },
  { label: "Desserts", categories: ["desserts", "milkshakes", "mastanis", "ice-cream"], emoji: "🍨" },
];

export const allCategories: MenuCategory[] = [
  "beverages", "refreshments", "sandwiches", "snacks", "south-india",
  "soups", "pizzas", "pav-bhaji", "tandoori", "hindustani",
  "breads", "rice", "chinese-starters", "chinese-mains", "sizzlers",
  "salads", "desserts", "milkshakes", "mastanis", "juices", "ice-cream",
];

// ─── MENU ITEMS ───────────────────────────────────────────────────────────────

export const menuItems: MenuItem[] = [
  // BEVERAGES
  { id: "bev1", name: "Tea", description: "Classic hot Indian chai", price: 43, category: "beverages" },
  { id: "bev2", name: "Coffee", description: "Hot freshly brewed coffee", price: 58, category: "beverages" },
  { id: "bev3", name: "SPL Filter Coffee", description: "South Indian style filter coffee", price: 60, category: "beverages", isPopular: true },
  { id: "bev4", name: "Green Tea", description: "Light and refreshing green tea", price: 55, category: "beverages" },
  { id: "bev5", name: "Hot Chocolate", description: "Rich and creamy hot chocolate", price: 159, category: "beverages" },

  // REFRESHMENTS
  { id: "ref1", name: "Jaljeera Soda", description: "Refreshing jaljeera with soda", price: 90, category: "refreshments" },
  { id: "ref2", name: "Fresh Lime Soda", description: "Freshly squeezed lime with chilled soda", price: 90, category: "refreshments", isPopular: true },
  { id: "ref3", name: "Mineral Water", description: "Packaged mineral water", price: 20, category: "refreshments" },
  { id: "ref4", name: "Cold Drinks", description: "Assorted cold beverages", price: 20, category: "refreshments" },
  { id: "ref5", name: "Delhi Lassi", description: "Thick creamy Delhi-style lassi", price: 99, category: "refreshments" },

  // SANDWICHES
  { id: "san1", name: "Veg Sandwich", description: "Fresh vegetables layered between bread with a light, flavorful spread", price: 100, category: "sandwiches", priceVariant: "100 / 145 (Cheese)" },
  { id: "san2", name: "SH SPL. Grilled Sandwich", description: "Grilled bread with Bombay masala filling and cheese", price: 179, category: "sandwiches", isPopular: true },
  { id: "san3", name: "Cheese Chilli Toast", description: "Bread toasted with baked cheese and green chillies", price: 160, category: "sandwiches" },
  { id: "san4", name: "Cheese Toast Veg. Sandwich", description: "Toasted bread with cheese and vegetables", price: 159, category: "sandwiches" },
  { id: "san5", name: "Cheese Garlic Toast", description: "Crispy toasted bread topped with melted cheese, garlic butter, and herbs", price: 139, category: "sandwiches" },
  { id: "san6", name: "Club Sandwich", description: "A layered sandwich stacked with vegetables, cheese, and toasted bread", price: 179, category: "sandwiches" },

  // ALL DAY SNACKS
  { id: "sna1", name: "Veg Cutlet", description: "Blend of vegetables, green peas, beetroot, potato and Indian spices with bread slice", price: 135, category: "snacks" },
  { id: "sna2", name: "French Fries", description: "Crispy golden finger chips — popularly known in India as finger chips", price: 130, category: "snacks", isPopular: true },
  { id: "sna3", name: "Channa Bhatura", description: "Spiced chickpea masala served with fluffy bhatura", price: 219, category: "snacks" },

  // TASTE OF SOUTH INDIA
  { id: "si1", name: "Idli Sambar", description: "Soft steamed rice cakes served with sambar and chutneys", price: 105, category: "south-india" },
  { id: "si2", name: "Idli Vada Sambar", description: "Idli and medu vada served with sambar and chutneys", price: 115, category: "south-india" },
  { id: "si3", name: "Medu Vada Sambar", description: "Crispy medu vadas served with sambar and chutneys", price: 115, category: "south-india" },
  { id: "si4", name: "Batata Vada Sambar", description: "Spiced potato vada served with sambar", price: 115, category: "south-india" },
  { id: "si5", name: "Sabudana Vada", description: "Crispy sabudana and potato vadas", price: 115, category: "south-india" },
  { id: "si6", name: "Masala Dosa", description: "Crispy dosa with spiced potato filling served with sambar and chutneys", price: 135, category: "south-india", isPopular: true },
  { id: "si7", name: "Sada Dosa", description: "Plain crispy dosa served with sambar and chutneys", price: 115, category: "south-india" },
  { id: "si8", name: "Mysore Masala Dosa", description: "Dosa with Mysore chutney and spiced potato filling", price: 149, category: "south-india", isPopular: true },
  { id: "si9", name: "Mysore Sada Dosa", description: "Plain dosa with Mysore chutney", price: 125, category: "south-india" },
  { id: "si10", name: "Rava Masala Dosa", description: "Semolina dosa with spiced potato filling", price: 135, category: "south-india" },
  { id: "si11", name: "Rava Sada Dosa", description: "Plain semolina dosa", price: 120, category: "south-india" },
  { id: "si12", name: "Onion Uttapa", description: "Thick rice pancake topped with onions", price: 125, category: "south-india" },
  { id: "si13", name: "Cheese Onion Uttapa", description: "Thick rice pancake topped with cheese and onions", price: 160, category: "south-india" },
  { id: "si14", name: "Tomato Onion Uttapa", description: "Thick rice pancake topped with tomato and onions", price: 130, category: "south-india" },
  { id: "si15", name: "Tomato Omelette", description: "South Indian style tomato omelette", price: 135, category: "south-india" },

  // SOUPS
  { id: "sou1", name: "Cream of Tomato", description: "Comforting creamy tomato soup with a silky texture", price: 155, category: "soups", isPopular: true },
  { id: "sou2", name: "Minestrone Soup", description: "Tomato soup base with beetroot, carrots, cheese, and boiled noodles", price: 170, category: "soups" },
  { id: "sou3", name: "Cream of Spinach", description: "Smooth spinach soup blended with cream and mild spices", price: 160, category: "soups" },
  { id: "sou4", name: "Manchow Soup", description: "Spicy Indo-Chinese soup with vegetables and crunchy noodles", price: 155, category: "soups" },
  { id: "sou5", name: "Hot N Sour Soup", description: "Classic Indo-Chinese soup with a perfect hot and sour balance", price: 155, category: "soups" },
  { id: "sou6", name: "Veg Clear", description: "Healthy clear soup with mixed vegetables", price: 155, category: "soups" },
  { id: "sou7", name: "Sweet Corn Soup", description: "Warm vegetable soup loaded with sweet corn goodness", price: 160, category: "soups" },
  { id: "sou8", name: "Thukpa Soup", description: "Warm, comforting noodle soup with mixed vegetables in a mildly spiced broth", price: 189, category: "soups" },

  // PIZZAS
  { id: "piz1", name: "Veg Pizza", description: "Classic veg pizza loaded with toppings", price: 220, category: "pizzas" },
  { id: "piz2", name: "Hawaiian Pizza", description: "Tropical-style pizza topped with pineapple and rich cheese", price: 275, category: "pizzas" },
  { id: "piz3", name: "Paneer Babycorn Pizza", description: "Delightful pizza topped with paneer, babycorn, and melted cheese", price: 299, category: "pizzas", isPopular: true },

  // PAV BHAJI
  { id: "pb1", name: "Pav Bhaji", description: "Spicy mashed vegetables cooked in butter, served with soft pav", price: 170, category: "pav-bhaji", priceVariant: "170 / 200 (Cheese)", isPopular: true },
  { id: "pb2", name: "Khada Pav Bhaji", description: "Traditional khada-style bhaji with visible veggies and desi spices", price: 200, category: "pav-bhaji" },
  { id: "pb3", name: "Masala Pav", description: "Mumbai style butter-tossed pav cooked with spicy onion-tomato masala", price: 130, category: "pav-bhaji" },

  // TANDOORI SNACKS
  { id: "tan1", name: "Paneer Tikka", description: "Smoky, char-grilled paneer with classic Indian tikka masala", price: 290, category: "tandoori", isPopular: true },
  { id: "tan2", name: "Paneer Banjara Kabab", description: "Char-grilled paneer infused with traditional Banjara-style masala", price: 299, category: "tandoori" },
  { id: "tan3", name: "Mix Veg Tikka", description: "Smoky tandoor-style vegetables with bold Indian spices", price: 299, category: "tandoori" },
  { id: "tan4", name: "Veg Seekh Kabab", description: "Mixed vegetables shaped on skewers and grilled in tandoor", price: 279, category: "tandoori" },
  { id: "tan5", name: "Hara Bhara Kabab", description: "Spinach, peas, and potato kebabs lightly spiced and shallow-fried", price: 269, category: "tandoori" },

  // HINDUSTANI KHASIYAT (Main Course)
  { id: "hin1", name: "Paneer Palak", description: "Spinach green gravy with fried paneer, garlic — medium spicy", price: 280, category: "hindustani" },
  { id: "hin2", name: "Paneer Bhurji", description: "Grated paneer with Indian spices, capsicum and onion — medium spicy", price: 285, category: "hindustani" },
  { id: "hin3", name: "Paneer Butter Masala", description: "Rich red gravy with paneer — sweet taste", price: 280, category: "hindustani", isPopular: true },
  { id: "hin4", name: "Paneer Chatpata", description: "Brown gravy with paneer, capsicum, onion — medium spicy", price: 285, category: "hindustani" },
  { id: "hin5", name: "Paneer Lajawab", description: "Light brown gravy with paneer and capsicum — medium spicy", price: 285, category: "hindustani" },
  { id: "hin6", name: "Paneer Pasanda", description: "Red gravy with fried paneer square sandwich — medium taste", price: 309, category: "hindustani" },
  { id: "hin7", name: "Paneer Handi", description: "Dark brown gravy with kala masala, paneer and onion — medium to spicy", price: 289, category: "hindustani" },
  { id: "hin8", name: "Paneer Kadai", description: "Red thick gravy with paneer and capsicum — medium spicy", price: 289, category: "hindustani", isPopular: true },
  { id: "hin9", name: "Paneer Kali Mirch", description: "Dark brown gravy with kali mirch and paneer — spicy", price: 285, category: "hindustani" },
  { id: "hin10", name: "Paneer Tikka Masala", description: "Thick red gravy with paneer, capsicum, tomato, onion — medium spicy (speciality)", price: 289, category: "hindustani", isPopular: true },
  { id: "hin11", name: "Paneer Tava", description: "Paneer, onion, capsicum on sizzling tava — red thick gravy, medium spicy, high quantity", price: 359, category: "hindustani" },
  { id: "hin12", name: "Paneer Makhanwala", description: "Red gravy with mix veg and paneer — medium sweet", price: 285, category: "hindustani" },
  { id: "hin13", name: "Paneer Shahjani", description: "White gravy with paneer and smashed kaju — medium sweet", price: 299, category: "hindustani" },
  { id: "hin14", name: "Paneer Tadka", description: "Dark brown gravy with fried paneer and garlic tadka — spicy", price: 309, category: "hindustani" },
  { id: "hin15", name: "Paneer Chingari", description: "Red thick gravy — medium spicy", price: 309, category: "hindustani" },
  { id: "hin16", name: "Paneer Degchi", description: "Thick yellow gravy — medium spicy", price: 299, category: "hindustani" },
  { id: "hin17", name: "Diwani Handi (special)", description: "Green palak gravy with mix vegetables, paneer, mushroom, potato — medium spicy", price: 315, category: "hindustani" },
  { id: "hin18", name: "Special Golden Kofta", description: "Golden gravy with paneer and cheese kofta — sweet", price: 309, category: "hindustani" },
  { id: "hin19", name: "Methi Chaman", description: "Thick gravy with methi pakoda — medium spicy", price: 289, category: "hindustani" },
  { id: "hin20", name: "Cheese Angoori", description: "Yellow gravy with cheese ball — sweet gravy", price: 309, category: "hindustani" },
  { id: "hin21", name: "Veg Bhuna", description: "Thick red gravy with mix veg balls — medium spicy", price: 260, category: "hindustani" },
  { id: "hin22", name: "Veg Jaipuri", description: "Yellow gravy with cabbage, capsicum, paneer, onion, papad, dry fruits — sweet taste", price: 285, category: "hindustani" },
  { id: "hin23", name: "Veg Jal Frazy", description: "Brown gravy with mix vegetables, paneer, cheese — medium spicy (people's favourite)", price: 285, category: "hindustani", isPopular: true },
  { id: "hin24", name: "Veg Handi", description: "Dark brown gravy with kala masala, mix vegetables, paneer — medium to spicy", price: 289, category: "hindustani" },
  { id: "hin25", name: "Veg Parivar", description: "Red and green gravies — sweet and medium spicy", price: 315, category: "hindustani" },
  { id: "hin26", name: "Veg Begum Bahar", description: "Red and brown gravies with mix vegetables kofta — medium spicy", price: 315, category: "hindustani" },
  { id: "hin27", name: "Paneer Mutter Masala", description: "Brown gravy with green peas and paneer — medium spicy", price: 265, category: "hindustani" },
  { id: "hin28", name: "Paneer Banjara", description: "Light brown gravy with paneer square pieces and capsicum — medium spicy", price: 289, category: "hindustani" },
  { id: "hin29", name: "Veg Tava", description: "Mix vegetables on sizzling hot plate with mushroom, paneer — medium spicy, high quantity", price: 340, category: "hindustani" },
  { id: "hin30", name: "Veg Malwani", description: "Red gravy with mix vegetables and coconut paste — spicy", price: 285, category: "hindustani" },
  { id: "hin31", name: "Veg Amritsari", description: "Red gravy with cabbage, paneer, capsicum, onion — medium spicy", price: 289, category: "hindustani" },
  { id: "hin32", name: "Veg Do Pyaza", description: "Red gravy with carrots, potato, green peas, beans, onion — tangy taste", price: 270, category: "hindustani" },
  { id: "hin33", name: "Veg Chilli Milli", description: "Yellow gravy with cabbage, paneer, capsicum, onion — spicy", price: 289, category: "hindustani" },
  { id: "hin34", name: "Veg Jwala", description: "Red gravy with mix vegetables, paneer, cheese — spicy", price: 285, category: "hindustani" },
  { id: "hin35", name: "Veg Sham Savera", description: "Red gravy with paneer green pakoda — medium sweet taste", price: 310, category: "hindustani" },
  { id: "hin36", name: "Veg Patiala", description: "Red gravy with mix veg papad rolls and cheese — medium spicy", price: 315, category: "hindustani" },
  { id: "hin37", name: "Veg Adraki", description: "Dark brown gravy with kofta — spicy", price: 280, category: "hindustani" },
  { id: "hin38", name: "Veg Maratha", description: "Red gravy with mix vegetable finger pakoda and cheese — spicy", price: 280, category: "hindustani" },
  { id: "hin39", name: "Veg Lajawab", description: "Brown gravy with mix vegetables and paneer — medium spicy", price: 280, category: "hindustani" },
  { id: "hin40", name: "Lucknowi Kofta", description: "Red gravy with sweet kofta — medium spicy", price: 319, category: "hindustani" },
  { id: "hin41", name: "Veg Kolhapuri", description: "Red gravy with mix vegetables — spicy", price: 280, category: "hindustani" },
  { id: "hin42", name: "Veg Kadai", description: "Red gravy with mix vegetables and paneer — medium spicy", price: 270, category: "hindustani" },
  { id: "hin43", name: "Veg Kofta Curry", description: "Brown gravy with mix vegetables kofta — medium spicy", price: 289, category: "hindustani" },
  { id: "hin44", name: "Veg Kabab Masala", description: "Green gravy with hara bhara kabab, cheese, kaju — medium spicy", price: 289, category: "hindustani" },
  { id: "hin45", name: "Veg Mastani", description: "Yellow gravy, Jain mix veg subji — medium spicy", price: 279, category: "hindustani" },
  { id: "hin46", name: "Aloo Mutter", description: "Brown gravy with potato and green peas — medium spicy", price: 245, category: "hindustani" },
  { id: "hin47", name: "Dum Aloo Pahadi", description: "Dark brown gravy with kala masala and potato round pieces — medium spicy", price: 280, category: "hindustani" },
  { id: "hin48", name: "Kaju Masala", description: "Red gravy with kaju pieces — medium spicy", price: 299, category: "hindustani" },
  { id: "hin49", name: "Channa Masala", description: "Brown gravy with kabuli channa — medium spicy", price: 250, category: "hindustani" },
  { id: "hin50", name: "Lasooni Methi", description: "Dry sabji with methi, garlic, crush groundnuts — medium spicy", price: 245, category: "hindustani" },
  { id: "hin51", name: "Malai Kofta", description: "Yellow gravy with paneer and aloo kofta, cherry, dry fruits — sweet taste", price: 285, category: "hindustani", isPopular: true },
  { id: "hin52", name: "Mushroom Handi", description: "Brown gravy with mushroom, tomato, onion — medium spicy", price: 299, category: "hindustani" },
  { id: "hin53", name: "Mushroom Masala", description: "Brown gravy with mushroom and onion — medium spicy", price: 289, category: "hindustani" },
  { id: "hin54", name: "Mushroom Pahadi", description: "Red gravy with mushroom — medium spicy", price: 289, category: "hindustani" },
  { id: "hin55", name: "Dal Fry", description: "Tuur dal — medium spicy", price: 175, category: "hindustani" },
  { id: "hin56", name: "Dal Tadka", description: "Tuur dal with mirchi tadka — spicy", price: 185, category: "hindustani" },

  // BREADS
  { id: "bre1", name: "Roti", description: "Plain tandoor roti", price: 28, category: "breads", priceVariant: "28 / 34 (Butter)" },
  { id: "bre2", name: "Gehu Roti", description: "Whole wheat tandoor roti", price: 28, category: "breads", priceVariant: "28 / 34 (Butter)" },
  { id: "bre3", name: "Nan", description: "Soft leavened tandoor bread", price: 75, category: "breads", priceVariant: "75 / 89 (Butter)" },
  { id: "bre4", name: "Paratha", description: "Layered tandoor bread", price: 75, category: "breads", priceVariant: "75 / 89 (Butter)" },
  { id: "bre5", name: "Cheese Garlic Nan", description: "Tandoor nan topped with melted cheese and garlic butter", price: 149, category: "breads", isPopular: true },
  { id: "bre6", name: "Butter Kulcha", description: "Soft kulcha with butter", price: 79, category: "breads" },
  { id: "bre7", name: "Garlic Kulcha", description: "Kulcha with garlic", price: 79, category: "breads" },
  { id: "bre8", name: "Aloo Paratha", description: "Stuffed potato paratha from the tandoor", price: 129, category: "breads" },

  // RICE
  { id: "ric1", name: "Steam Rice", description: "Plain steamed rice", price: 165, category: "rice", priceVariant: "165 / 179 (Jeera)" },
  { id: "ric2", name: "Curd Rice", description: "Rice cooked with curd, optional mirchi tadka", price: 235, category: "rice" },
  { id: "ric3", name: "Veg Biryani", description: "Fragrant basmati rice cooked with mixed vegetables and aromatic spices", price: 270, category: "rice", isPopular: true },
  { id: "ric4", name: "Veg Pulav", description: "Aromatic basmati rice cooked with mixed vegetables and whole spices", price: 219, category: "rice" },
  { id: "ric5", name: "Dal Khichadi", description: "Classic tuur dal Indian khichdi — healthy and easy to digest", price: 229, category: "rice" },
  { id: "ric6", name: "Dal Khichadi Kadhi", description: "Dal khichadi served with kadhi", price: 260, category: "rice" },
  { id: "ric7", name: "SPL Handi Biryani", description: "Vegetables and gravy inside with paneer, carrot, beans, green peas and curd — medium spicy", price: 289, category: "rice", isPopular: true },
  { id: "ric8", name: "Banarasi Biryani", description: "Fragrant rice cooked with aromatic spices in traditional Banarasi style", price: 279, category: "rice" },

  // CHINESE STARTERS
  { id: "chi1", name: "Paneer Chilli", description: "Paneer with green chilli, onion, capsicum and soya sauce — medium spicy", price: 275, category: "chinese-starters", isPopular: true },
  { id: "chi2", name: "Paneer Schezwan", description: "Schezwan sauce with red chilli and paneer — spicy", price: 285, category: "chinese-starters" },
  { id: "chi3", name: "Paneer 65", description: "Paneer with capsicum, onion, kaju and schezwan sauce — spicy tangy taste", price: 290, category: "chinese-starters" },
  { id: "chi4", name: "Paneer Cheese Combo (special)", description: "Paneer, cheese, babycorn on stick — medium spicy", price: 315, category: "chinese-starters", isPopular: true },
  { id: "chi5", name: "Veg Manchurian", description: "Cabbage balls with soya sauce and red chilli — medium spicy", price: 259, category: "chinese-starters" },
  { id: "chi6", name: "Veg Crispy", description: "Carrots and beans fried and made crispy with coating of Chinese sauces", price: 260, category: "chinese-starters" },
  { id: "chi7", name: "Veg Green Chilli", description: "Cabbage, capsicum, onion with green Chinese sauce — medium spicy", price: 260, category: "chinese-starters" },
  { id: "chi8", name: "Soya Bean Chilli", description: "Soya bean, capsicum, onion with soya sauce and red chilli — medium spicy", price: 260, category: "chinese-starters" },
  { id: "chi9", name: "Spring Roll", description: "Cabbage, noodles, schezwan chatni and sauces — medium spicy, fried", price: 285, category: "chinese-starters" },
  { id: "chi10", name: "Shanghai Roll", description: "Cabbage, schezwan chatni, garlic, ginger with red chilli sauce — medium spicy, fried with cheese", price: 285, category: "chinese-starters" },
  { id: "chi11", name: "Chinese Dosa", description: "Dosa with filling of schezwan chatni and noodles", price: 260, category: "chinese-starters" },
  { id: "chi12", name: "Crispy Corn", description: "American corn made crispy with coating of Chinese sauces", price: 260, category: "chinese-starters" },
  { id: "chi13", name: "Cheese Ball Sesame", description: "Fried cheese ball with mix vegetable finger and red sauce", price: 299, category: "chinese-starters" },
  { id: "chi14", name: "Mushroom Chilli", description: "Fried mushroom with capsicum, onion and soya sauce — medium spicy", price: 249, category: "chinese-starters" },
  { id: "chi15", name: "Honey Chilli Potato", description: "Crispy fried potatoes tossed in sweet, spicy honey-chilli glaze with garlic and sesame", price: 239, category: "chinese-starters", isPopular: true },

  // CHINESE MAINS
  { id: "chm1", name: "Hakka Noodles", description: "Noodles with cabbage, onion, capsicum — medium spicy", price: 239, category: "chinese-mains", isPopular: true },
  { id: "chm2", name: "Schezwan Noodles", description: "Noodles with cabbage, onion, capsicum and schezwan sauce — spicy", price: 239, category: "chinese-mains" },
  { id: "chm3", name: "Veg Fried Rice", description: "Fried rice with beans and carrot — medium spicy", price: 239, category: "chinese-mains" },
  { id: "chm4", name: "Schezwan Fried Rice", description: "Fried rice with beans, carrots and schezwan sauce — spicy", price: 239, category: "chinese-mains" },
  { id: "chm5", name: "American Chopsuey", description: "Crispy noodles with cabbage, tomato sauce, pineapple, capsicum, onion — sweet tangy taste", price: 289, category: "chinese-mains", isPopular: true },
  { id: "chm6", name: "Veg Triple Schezwan", description: "Rice and noodles mix with manchurian gravy and schezwan sauce — spicy", price: 309, category: "chinese-mains" },
  { id: "chm7", name: "Mushroom Fried Rice", description: "Classic fried rice tossed with fresh mushrooms and vegetables", price: 239, category: "chinese-mains" },
  { id: "chm8", name: "Singapuri Noodles", description: "Classic Singapore-style noodles with veggies and bold flavors", price: 249, category: "chinese-mains" },

  // SIZZLERS & CONTINENTAL
  { id: "siz1", name: "Veg Au Gratin", description: "Mix vegetables in white sauce baked with cheese and pineapple — sweet taste", price: 359, category: "sizzlers" },
  { id: "siz2", name: "Veg Sizzler", description: "Mix vegetable cutlet, french fries, stuffed tomato, stuffed simla — medium spicy, with rice", price: 399, category: "sizzlers", isPopular: true },
  { id: "siz3", name: "Chinese Sizzler", description: "Manchurian, paneer chilli, rice, singapori noodles — medium spicy", price: 399, category: "sizzlers" },
  { id: "siz4", name: "Continental Sizzler", description: "Mix veg in white sauce, spaghetti or noodles in white sauce, stuffed capsicum and tomato", price: 399, category: "sizzlers" },
  { id: "siz5", name: "Paneer Shashlik Sizzler", description: "Mix veg with large paneer pieces, french fries, stuffed tomato and capsicum — medium spicy", price: 399, category: "sizzlers", isPopular: true },

  // SALADS, RAITAS & PAPADS
  { id: "sal1", name: "Green Salad", description: "Cucumber, carrots, tomato, beetroot, cabbage", price: 119, category: "salads" },
  { id: "sal2", name: "Boondi Raita", description: "Boondi mixed in salted curd", price: 139, category: "salads" },
  { id: "sal3", name: "Pineapple Raita", description: "Pineapple pieces mixed in sweet curd", price: 169, category: "salads" },
  { id: "sal4", name: "Masala Papad", description: "Fried papad topped with shev, tomato, onion, coriander and chaat masala", price: 69, category: "salads" },
  { id: "sal5", name: "Mix Raita", description: "Mix cucumber, tomato, onion in tangy curd", price: 129, category: "salads" },

  // DESSERTS
  { id: "des1", name: "Cadbury Crescendo", description: "Chocolate ice cream, choco chips ice cream, chocolate sauce, Kit Kat, choco wafer stick", price: 259, category: "desserts", isPopular: true },
  { id: "des2", name: "Sizzling Brownie", description: "Chocolate brownie with vanilla ice cream, choco sauce and kaju on a sizzling plate", price: 239, category: "desserts", isPopular: true },
  { id: "des3", name: "Double Sundae", description: "Fruit salad with pineapple ice cream, gulkand ice cream, topped with dry fruits", price: 249, category: "desserts" },
  { id: "des4", name: "Traffic Jam", description: "Fresh jam with butter scotch, mango, vanilla, kesar pista — topped with dry fruits", price: 249, category: "desserts" },
  { id: "des5", name: "Watermelon Delight", description: "Watermelon pieces, vanilla milkshake, watermelon ice cream with fresh cream", price: 249, category: "desserts", isSeasonal: true },
  { id: "des6", name: "Fresh Strawberry with Cream", description: "Fresh strawberry pieces, strawberry ice cream with fresh whipped cream", price: 249, category: "desserts", isSeasonal: true },
  { id: "des7", name: "Mango with Cream", description: "Fresh mango pieces, mango ice cream with fresh whipped cream", price: 249, category: "desserts", isSeasonal: true },
  { id: "des8", name: "Fruit Salad with Ice Cream", description: "Fresh fruits with ice cream", price: 209, category: "desserts" },
  { id: "des9", name: "Chocolate Avalanche", description: "Chocolate cake with vanilla and chocolate ice cream, chocolate sauce and choco chips", price: 349, category: "desserts", isPopular: true },

  // MILKSHAKES
  { id: "mil1", name: "Apple Milkshake", description: "Fresh apple milkshake", price: 170, category: "milkshakes" },
  { id: "mil2", name: "Badam Milkshake", description: "Rich almond milkshake", price: 209, category: "milkshakes" },
  { id: "mil3", name: "Chikku Milkshake", description: "Creamy sapodilla milkshake", price: 149, category: "milkshakes" },
  { id: "mil4", name: "Chocolate Milkshake", description: "Thick chocolate milkshake", price: 169, category: "milkshakes" },
  { id: "mil5", name: "Cold Coffee", description: "Chilled frothy cold coffee", price: 179, category: "milkshakes", isPopular: true },
  { id: "mil6", name: "Kesar Thandai Milkshake", description: "Traditional thandai with kesar — cold and refreshing", price: 209, category: "milkshakes" },
  { id: "mil7", name: "Mango Milkshake", description: "Fresh mango milkshake", price: 209, category: "milkshakes", isPopular: true },
  { id: "mil8", name: "Mix Fruit Milkshake", description: "Blend of fresh seasonal fruits", price: 179, category: "milkshakes" },
  { id: "mil9", name: "Oreo Milkshake", description: "Creamy milkshake blended with Oreo cookies", price: 240, category: "milkshakes", isPopular: true },
  { id: "mil10", name: "Pineapple Milkshake", description: "Refreshing pineapple milkshake", price: 169, category: "milkshakes" },
  { id: "mil11", name: "Rose Milkshake", description: "Chilled rose-flavored milkshake", price: 179, category: "milkshakes" },
  { id: "mil12", name: "Sitafal Milkshake", description: "Custard apple milkshake", price: 289, category: "milkshakes", isSeasonal: true },
  { id: "mil13", name: "Strawberry Milkshake", description: "Fresh strawberry milkshake", price: 179, category: "milkshakes" },
  { id: "mil14", name: "Vanilla Milkshake", description: "Classic vanilla milkshake", price: 159, category: "milkshakes" },

  // MASTANIS & FALOODAS
  { id: "mas1", name: "Dry Fruit Mastani", description: "Dry fruits blended with delicious milkshakes and ice cream", price: 229, category: "mastanis" },
  { id: "mas2", name: "Sweet Home SPL. Mastani", description: "Signature Sweet Home mastani — worth a try!", price: 229, category: "mastanis", isPopular: true },
  { id: "mas3", name: "Mango Mastani", description: "Signature Sweet Home mango mastani — worth a try!", price: 220, category: "mastanis", isPopular: true },
  { id: "mas4", name: "Rose Falooda", description: "Rose syrup, sabja, shevai, vanilla ice cream with tooti fruity", price: 209, category: "mastanis" },
  { id: "mas5", name: "Kesar Falooda", description: "Kesar syrup, sabja, shevai, vanilla ice cream with tooti fruity", price: 229, category: "mastanis" },
  { id: "mas6", name: "SPL. Dry Fruit Falooda", description: "Dry fruits, kesar syrup, sabja, shevai, vanilla ice cream with tooti fruity — with a different twist", price: 229, category: "mastanis" },

  // FRESH FRUIT JUICES
  { id: "jui1", name: "Mosamby Juice", description: "Fresh sweet lime juice", price: 139, category: "juices" },
  { id: "jui2", name: "Orange Juice", description: "Fresh squeezed orange juice", price: 139, category: "juices" },
  { id: "jui3", name: "Pineapple Juice", description: "Fresh pineapple juice", price: 129, category: "juices" },
  { id: "jui4", name: "Watermelon Juice", description: "Fresh watermelon juice", price: 159, category: "juices" },
  { id: "jui5", name: "Grapes Juice", description: "Fresh grapes juice", price: 159, category: "juices" },
  { id: "jui6", name: "Cocktail Juice", description: "Mix fresh fruit juice", price: 169, category: "juices" },
  { id: "jui7", name: "Ganga Jamuna", description: "Two-color fresh fruit juice blend", price: 159, category: "juices" },
  { id: "jui8", name: "Pomegranate Juice", description: "Fresh anar juice", price: 169, category: "juices", isPopular: true },
  { id: "jui9", name: "Apple Juice", description: "Fresh apple juice", price: 169, category: "juices" },
  { id: "jui10", name: "Carrot Juice", description: "Fresh carrot juice", price: 119, category: "juices" },
  { id: "jui11", name: "Anar Pineapple Juice", description: "Fresh pomegranate and pineapple blend", price: 169, category: "juices" },
  { id: "jui12", name: "Mango Juice", description: "Fresh mango juice", price: 189, category: "juices", isSeasonal: true },

  // NATURAL ICE CREAM
  { id: "ice1", name: "Malai Vanilla", description: "Classic natural malai vanilla ice cream", price: 85, category: "ice-cream" },
  { id: "ice2", name: "Kesar Pista", description: "Rich saffron and pistachio natural ice cream", price: 90, category: "ice-cream", isPopular: true },
  { id: "ice3", name: "Dry Anjeer", description: "Natural fig ice cream", price: 90, category: "ice-cream" },
  { id: "ice4", name: "SPL. Thandai", description: "Special thandai flavor natural ice cream", price: 90, category: "ice-cream" },
  { id: "ice5", name: "Butter Scotch", description: "Creamy butterscotch natural ice cream", price: 90, category: "ice-cream" },
  { id: "ice6", name: "Roasted Almond", description: "Natural ice cream with roasted almonds", price: 90, category: "ice-cream" },
  { id: "ice7", name: "Gulkand", description: "Rose petal preserve natural ice cream", price: 90, category: "ice-cream" },
  { id: "ice8", name: "Mango Ice Cream", description: "Natural mango ice cream", price: 90, category: "ice-cream" },
  { id: "ice9", name: "Choco Chips", description: "Natural ice cream with chocolate chips", price: 90, category: "ice-cream" },
  { id: "ice10", name: "SPL. Pan Masala", description: "Meetha paan flavored natural ice cream", price: 90, category: "ice-cream" },
  { id: "ice11", name: "Fresh Strawberry", description: "Natural fresh strawberry ice cream", price: 100, category: "ice-cream", isSeasonal: true },
  { id: "ice12", name: "Fresh Pineapple", description: "Natural fresh pineapple ice cream", price: 100, category: "ice-cream", isSeasonal: true },
  { id: "ice13", name: "Fresh Mango", description: "Natural fresh mango ice cream", price: 100, category: "ice-cream", isSeasonal: true },
  { id: "ice14", name: "Fresh Chikku", description: "Natural fresh sapodilla ice cream", price: 100, category: "ice-cream", isSeasonal: true },
  { id: "ice15", name: "Fresh Guava", description: "Natural fresh guava ice cream", price: 100, category: "ice-cream", isSeasonal: true },
  { id: "ice16", name: "Fresh Leechi", description: "Natural fresh lychee ice cream", price: 100, category: "ice-cream", isSeasonal: true },
  { id: "ice17", name: "Tender Coconut", description: "Natural tender coconut ice cream", price: 100, category: "ice-cream", isSeasonal: true },
  { id: "ice18", name: "Fresh Sitafal", description: "Natural fresh custard apple ice cream", price: 100, category: "ice-cream", isSeasonal: true },
];
